server:
  port: 8080

mybatis:
  mapperLocations: classpath:mapper/*.xml
  #typeAliasesPackage: com.example.demo.entity

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/world
    #?serverTimezone=GMT&useSSL=false
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:                                          # 进行数据库连接池的配置
      min-idle: 5                                   # 数据库连接池的最小维持连接数
      initial-size: 5                               # 初始化提供的连接数
      max-total: 5                                  # 最大的连接数
      max-wait-millis: 200                          # 等待连接获取的最大超时时间
      type: com.alibaba.druid.pool.DruidDataSource  # druid 数据源
